M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 12:34:57 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T12:34:57-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.6909Y-4.1909
X5.7Y-4.1
X5.7188Y-4.2188
X5.9Y-4.5
X6.0Y-4.8
T2
X5.5732Y-3.439
X5.5732Y-3.639
T0
M30
